
#ifndef TIXAMLLISTVIEW_EXPORT_H
#define TIXAMLLISTVIEW_EXPORT_H

#ifdef TIXAMLLISTVIEW_STATIC_DEFINE
#  define TIXAMLLISTVIEW_EXPORT
#  define TIXAMLLISTVIEW_NO_EXPORT
#else
#  ifndef TIXAMLLISTVIEW_EXPORT
#    ifdef TiXamlListView_EXPORTS
        /* We are building this library */
#      define TIXAMLLISTVIEW_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define TIXAMLLISTVIEW_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef TIXAMLLISTVIEW_NO_EXPORT
#    define TIXAMLLISTVIEW_NO_EXPORT 
#  endif
#endif

#ifndef TIXAMLLISTVIEW_DEPRECATED
#  define TIXAMLLISTVIEW_DEPRECATED 
#endif

#ifndef TIXAMLLISTVIEW_DEPRECATED_EXPORT
#  define TIXAMLLISTVIEW_DEPRECATED_EXPORT TIXAMLLISTVIEW_EXPORT TIXAMLLISTVIEW_DEPRECATED
#endif

#ifndef TIXAMLLISTVIEW_DEPRECATED_NO_EXPORT
#  define TIXAMLLISTVIEW_DEPRECATED_NO_EXPORT TIXAMLLISTVIEW_NO_EXPORT TIXAMLLISTVIEW_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef TIXAMLLISTVIEW_NO_DEPRECATED
#    define TIXAMLLISTVIEW_NO_DEPRECATED
#  endif
#endif

#endif
